on:
  issues:
    types: [opened]
    
name: Jira sync jobs

jobs:
  create-ticket-on-issue-opened:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: MAD
        issuetype: Bug
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}

    - name: Setup
      uses: atlassian/gajira-cli@v3
      with:
        version: 1.0.27
        
    - name: Change component to Android
      run: jira --issue=${{steps.create.outputs.issue}} --components="Android" --epic="MAD-8"
      
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
